version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      security:
        patterns:
          - "*"
        update-types:
          - "security"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
