<#
.SYNOPSIS
  Guided NR2 Office Workstation setup — station name, HAL hub URL, shortcuts, optional startup.
#>
[CmdletBinding()]
param(
    [string]$Station,
    [string]$HalHubUrl,
    [switch]$NoStartup,
    [switch]$Quiet,
    [switch]$SkipPythonBootstrap
)

$ErrorActionPreference = 'Stop'
$PkgRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$AppDir = Join-Path $PkgRoot 'NewRidgeFinancial2'
$EnvPath = Join-Path $PkgRoot '.env'
$EnvExample = Join-Path $PkgRoot '.env.example'
$Launcher = Join-Path $PkgRoot 'Start-NR2-Workstation.bat'
$HiddenLauncher = Join-Path $PkgRoot 'Start-NR2-Workstation-Hidden.bat'
$Icon = Join-Path $PkgRoot 'assets\nr2-icon.ico'
$ReqFile = Join-Path $AppDir 'requirements-workstation.txt'
$PythonDir = Join-Path $PkgRoot 'python'
$PythonW = Join-Path $PythonDir 'Scripts\pythonw.exe'

function Write-Info($msg) { if (-not $Quiet) { Write-Host $msg } }

function Get-Slug([string]$value) {
    if ($null -eq $value) { $value = '' }
    $s = $value.ToLowerInvariant()
    $s = [regex]::Replace($s, '[^a-z0-9]+', '-')
    $s = $s.Trim('-')
    if ([string]::IsNullOrWhiteSpace($s)) { return 'unknown' }
    return $s
}

function Find-SystemPythonForVenv {
    $pyLauncher = Get-Command 'py' -ErrorAction SilentlyContinue
    if ($pyLauncher) {
        foreach ($ver in @('-3.13', '-3.12', '-3.11')) {
            try {
                & $pyLauncher.Source $ver -c "import sys; print(sys.version_info >= (3, 11))" 2>$null | Out-Null
                if ($LASTEXITCODE -eq 0) {
                    return @{ Mode = 'py'; Exe = $pyLauncher.Source; VersionArg = $ver }
                }
            } catch { continue }
        }
        return @{ Mode = 'py'; Exe = $pyLauncher.Source; VersionArg = '' }
    }
    $python = Get-Command 'python' -ErrorAction SilentlyContinue
    if ($python) {
        return @{ Mode = 'direct'; Exe = $python.Source; VersionArg = '' }
    }
    return $null
}

function Bootstrap-PackagedPython {
    if ($SkipPythonBootstrap -and (Test-Path $PythonW)) { return }
    if (Test-Path $PythonW) {
        Write-Info "Bundled Python OK: $PythonW"
        return
    }
    Write-Info 'Creating bundled Python runtime (one-time; may need network for pip)...'
    $sys = Find-SystemPythonForVenv
    if (-not $sys) {
        throw @"
Python 3.11+ is required to finish setup on this PC.
Install Python from https://www.python.org/downloads/ (check "Add to PATH"), then run Install.bat again.
"@
    }
    if ($sys.Mode -eq 'py' -and $sys.VersionArg) {
        & $sys.Exe $sys.VersionArg -m venv $PythonDir --copies
    } elseif ($sys.Mode -eq 'py') {
        & $sys.Exe -m venv $PythonDir --copies
    } else {
        & $sys.Exe -m venv $PythonDir --copies
    }
    if (-not (Test-Path $PythonW)) {
        throw "Failed to create venv at $PythonDir"
    }
    $pip = Join-Path $PythonDir 'Scripts\pip.exe'
    if (-not (Test-Path $ReqFile)) {
        throw "Missing $ReqFile"
    }
    & $pip install --disable-pip-version-check -r $ReqFile
    if ($LASTEXITCODE -ne 0) { throw 'pip install failed for workstation requirements' }
    Write-Info "Python runtime ready at $PythonDir"
}

function Write-EnvFile {
    param(
        [string]$StationName,
        [string]$HubUrl,
        [string]$SidenotesHub
    )
    $lines = @(
        '# NR2 Office Workstation — generated by Setup-Workstation.ps1',
        "NR2_WORKSTATION_STATION=$StationName",
        "NR2_SIDENOTES_MY_STATION=$StationName",
        "NR2_HAL_HUB_URL=$HubUrl",
        'NR2_WORKSTATION_FAST_HAL=1',
        'NR2_WORKSTATION_START_HIDDEN=1',
        'NR2_WORKSTATION_PORT=8766',
        'NR2_HUB_POPUP_WATCHER=1',
        'NR2_SIDENOTES_POPUP_WATCHER=1',
        "NR2_SIDENOTES_HUB_DATA=$SidenotesHub"
    )
    $lines | Set-Content -Path $EnvPath -Encoding UTF8
}

function New-Shortcut {
    param(
        [string]$LinkPath,
        [string]$Description,
        [string]$Target = $Launcher
    )
    $shell = New-Object -ComObject WScript.Shell
    $shortcut = $shell.CreateShortcut($LinkPath)
    $shortcut.TargetPath = $Target
    $shortcut.WorkingDirectory = $PkgRoot
    if (Test-Path $Icon) { $shortcut.IconLocation = "$Icon,0" }
    $shortcut.Description = $Description
    $shortcut.WindowStyle = 7
    $shortcut.Save()
}

Write-Info ''
Write-Info '==================================================='
Write-Info '  NR2 Office Workstation Setup'
Write-Info '==================================================='
Write-Info ''

Bootstrap-PackagedPython

$knownStations = @(
    'Frontdesk 1', 'Frontdesk 2', 'Office Manager',
    'Room 1', 'Room 2', 'Room 3', 'Room 4', 'Room 5',
    'Server', 'Darkroom'
)
$defaultHub = 'http://127.0.0.1:8765'
$defaultSidenotesHub = 'C:\softdent\HAL-SideNotes-Workstation\data'

if (-not $Station) {
    Write-Info 'Which station is THIS computer? (Must match SideNotes / office routing.)'
    Write-Info ''
    for ($i = 0; $i -lt $knownStations.Count; $i++) {
        Write-Info ("  {0}. {1}" -f ($i + 1), $knownStations[$i])
    }
    Write-Info ''
    $ans = Read-Host "Station (number or name) [default: $env:COMPUTERNAME]"
    if ([string]::IsNullOrWhiteSpace($ans)) {
        $Station = $env:COMPUTERNAME
    } elseif ($ans -match '^[0-9]+$' -and [int]$ans -ge 1 -and [int]$ans -le $knownStations.Count) {
        $Station = $knownStations[[int]$ans - 1]
    } else {
        $Station = $ans.Trim()
    }
}

if (-not $HalHubUrl) {
    Write-Info ''
    Write-Info 'HAL hub URL — the Start Program PC on your office LAN (port 8765).'
    Write-Info "Example: http://192.168.1.50:8765"
    Write-Info ''
    $HalHubUrl = (Read-Host "HAL hub URL [$defaultHub]").Trim()
    if ([string]::IsNullOrWhiteSpace($HalHubUrl)) { $HalHubUrl = $defaultHub }
}

$slug = Get-Slug $Station
Write-Info ''
Write-Info "Station: $Station"
Write-Info "HAL hub:  $HalHubUrl"

Write-EnvFile -StationName $Station -HubUrl $HalHubUrl -SidenotesHub $defaultSidenotesHub

$stationFile = Join-Path (Join-Path $PkgRoot 'app_data\nr2') 'workstation-popup-station.json'
New-Item -ItemType Directory -Force -Path (Split-Path $stationFile) | Out-Null
(@{ station = $Station; updatedAt = (Get-Date).ToUniversalTime().ToString('o') } | ConvertTo-Json) | Set-Content $stationFile -Encoding UTF8

$desktops = @([Environment]::GetFolderPath('Desktop'))
try {
    $reg = Get-ItemProperty 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders' -ErrorAction SilentlyContinue
    if ($reg -and $reg.Desktop) {
        $expanded = [Environment]::ExpandEnvironmentVariables([string]$reg.Desktop)
        if ($expanded -and (Test-Path $expanded) -and $desktops -notcontains $expanded) {
            $desktops += $expanded
        }
    }
} catch {}

$manifestPath = Join-Path $AppDir 'nr2-build.json'
$schemaVersion = 'unknown'
if (Test-Path $manifestPath) {
    try {
        $manifest = Get-Content $manifestPath -Raw | ConvertFrom-Json
        if ($manifest.schemaVersion) { $schemaVersion = [string]$manifest.schemaVersion }
    } catch {}
}

foreach ($desktop in ($desktops | Select-Object -Unique)) {
    if (-not $desktop) { continue }
    $link = Join-Path $desktop 'NR2 Workstation.lnk'
    New-Shortcut -LinkPath $link -Description "NR2 Office Workstation ($schemaVersion)"
    Write-Info "Desktop shortcut: $link"
}

if (-not $NoStartup) {
    $register = Join-Path $PkgRoot 'Register-NR2WorkstationStartup.ps1'
    if (Test-Path $register) {
        & $register -PkgRoot $PkgRoot -Quiet:$Quiet
    } else {
        $startup = [Environment]::GetFolderPath('Startup')
        if ($startup) {
            $link = Join-Path $startup 'NR2 Workstation.lnk'
            New-Shortcut -LinkPath $link -Target $HiddenLauncher -Description "NR2 Office Workstation auto-start ($schemaVersion)"
            Write-Info "Startup shortcut: $link"
        }
    }
}

Write-Info ''
$startNow = 'y'
if (-not $Quiet) {
    $startNow = (Read-Host 'Start NR2 Workstation now? [Y/n]').Trim().ToLowerInvariant()
}
if ($startNow -eq '' -or $startNow -eq 'y' -or $startNow -eq 'yes') {
    & (Join-Path $PkgRoot 'Start-Workstation.ps1') -Hidden
}

Write-Info ''
Write-Info 'Done. Popups run in the background; open NR2 Workstation from the desktop to send messages or Ask HAL.'
