"""Moonshot AI — What HAL said (program improvements) + how to fix with coding.

CONSULT ONLY. Operator request VERBATIM. Await approval before applying code.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / ".local_logs" / "moonshot_financial_eval"
DOCS = REPO / "NewRidgeFinancial2" / "docs"
OUT.mkdir(parents=True, exist_ok=True)
DOCS.mkdir(parents=True, exist_ok=True)
DATE = datetime.now(timezone.utc).strftime("%Y-%m-%d")

HELPER = (
    REPO
    / "_archive"
    / "2026-07-10"
    / ".local_logs"
    / "moonshot_financial_eval"
    / "_run_moonshot_eval.py"
)
sys.path.insert(0, str(HELPER.parent))
from _run_moonshot_eval import extract_message_content, resolve_api_and_endpoint  # noqa: E402

OPERATOR_REQUEST_VERBATIM = """
ask moonshot ai  hat hal said and how to fix with coding and report - Based on the governed memory and payer reference data provided, here are potential improvements for the New Ridge Family Financial program:
1. **Workflow Automation:**
 * Automate denied claim tracking and assignment to Steve, rather than relying solely on manual queues or ad-hoc processes.
 * Streamline the process for narrative drafts needing Dr. Reno's sign-off (e.g., template-based suggestions, automated reminders).
 * Integrate EOB posting backlog management more tightly with other daily tasks.
2. **Data Accuracy and Consistency:**
 * Ensure seamless synchronization of carrier information (like fee schedules, eligibility phones) between SoftDent, the Office Insurance.xlsx workbook, and HAL.
 * Improve the accuracy of carrier labels generated by SoftDent to match the specific payer IDs or names used in routing/communication (e.g., distinguishing between different Anthem plans if necessary for workflow).
 * Centralize and easily update carrier contact information (eligibility/claim phones) so all systems (like HAL's "Remember") can reference it correctly without manual intervention.
3. **Knowledge Management & Updates:**
 * While the governed memory allows overriding older facts, improving the ease and frequency with which staff can provide new information or updates to HAL would be beneficial.
 * Perhaps develop a more structured way for staff to input policy changes or new learnings directly into HAL's update mechanism.
4. **Integration & Communication:**
 * Enhance the communication flow between HAL, SoftDent, and other internal systems regarding payer changes or updates (e.g., "Remember this" messages).
These improvements aim to reduce manual effort, minimize errors, increase efficiency in handling denials and narratives, and ensure everyone has access to the most current and accurate carrier information.
""".strip()

SYSTEM = """You are Moonshot AI (kimi-k2 class) — NR2 Apex + HAL systems architect for
NewRidge Family Financial (Kansas dental S-corp; SoftDent + QuickBooks imports;
local HTTPS starship-bridge).

CRITICAL CONSTRAINTS:
1. Answer the operator request VERBATIM: what HAL said, how to fix WITH CODING,
   and REPORT. CONSULT ONLY — DO NOT APPLY code until operator says approve/proceed.
2. Treat the quoted HAL answer as STAFF-FACING ADVICE grounded in governed memory
   + payer reference — not as already-shipped product features. Map each bullet to:
   (A) already exists in code, (B) partial / needs wiring, (C) net-new build.
3. Ground every coding fix in the LIVE FACTS + attached excerpts. Never invent
   dollars, claim IDs, patients, SoftDent write-back, or clinical facts.
4. Honesty rules: NR2-local audit/tasks only; HAL never submits claims; no SoftDent
   write-back from kanban; Remember this → learned_memories (no PHI/secrets);
   payer_reference.json is curated — sync FROM SoftDent/xlsx INTO NR2, not invent.
5. Prefer additive packs (apex_*_pack.py), board-actions, LocalStore keys, office_tasks
   assignee=Steve, narrative sign-off lanes, payer_reference_store — over new SaaS.
6. For EACH of HAL's 4 themes, give: diagnosis, coding plan, paste-ready file/function
   sketches (CONSULT ONLY), effort S/M/L, validation gate.
7. Rank a MUST / SHOULD / NICE build order that does not redo IMP-001..010 unless gap.
8. End with APPROVAL CHECKLIST — STOP until operator approves.

OUTPUT FORMAT (strict markdown):
# Verdict — What HAL meant + can we fix with code?
## 0. Operator Intent (quote; consult-only)
## 1. Decode HAL's Answer (source: memory/payer ref vs invent)
## 2. Gap Map vs Shipped (IMP-001..010 + payer_reference + Remember this)
Table: HAL bullet | Status (exists/partial/new) | Gap | Fix effort
## 3. Coding Fixes by Theme (1 Workflow / 2 Data / 3 Knowledge / 4 Integration)
Each: diagnosis → files to touch → paste-ready sketches → validation
## 4. Recommended Build Order (MUST / SHOULD / NICE) + Phases
## 5. Risks / PHI / SoftDent honesty / Rollback
## 6. Approval Checklist
DO NOT APPLY until operator says approve / proceed.
"""


def _truncate(text: str, max_lines: int) -> str:
    lines = text.splitlines()
    if len(lines) <= max_lines:
        return text
    return "\n".join(lines[:max_lines]) + f"\n... [{len(lines) - max_lines} lines truncated]"


def _extract_lines(path: Path, start_marker: str, end_marker: str | None, max_lines: int) -> str:
    if not path.is_file():
        return "(missing)"
    text = path.read_text(encoding="utf-8", errors="replace")
    start = text.find(start_marker)
    if start < 0:
        return f"(marker not found: {start_marker[:60]})"
    if end_marker:
        end = text.find(end_marker, start + len(start_marker))
        chunk = text[start : (end if end > start else start + 12000)]
    else:
        chunk = text[start : start + 12000]
    return _truncate(chunk, max_lines)


CONTEXT_FILES: list[tuple[str, int]] = [
    ("NewRidgeFinancial2/nr2-build.json", 12),
    ("NewRidgeFinancial2/docs/MOONSHOT_PROGRAM_IMPROVE_APPLIED_2026-07-10.md", 45),
    ("NewRidgeFinancial2/docs/MOONSHOT_PROGRAM_IMPROVE_CONSULT_2026-07-10.md", 80),
    ("NewRidgeFinancial2/site/hal-memo-index.js", 40),
]


def build_context() -> str:
    parts: list[str] = []
    for rel, max_lines in CONTEXT_FILES:
        path = REPO / rel
        if not path.is_file():
            parts.append(f"### FILE: {rel}\n(missing)")
            continue
        body = _truncate(path.read_text(encoding="utf-8", errors="replace"), max_lines)
        ext = path.suffix.lstrip(".") or "txt"
        parts.append(f"### FILE: {rel}\n```{ext}\n{body}\n```")

    backend = REPO / "NewRidgeFinancial2" / "apex_backend.py"
    parts.append(
        "### EXTRACT: apex_backend.py — teach HAL / Remember this\n```python\n"
        + _extract_lines(
            backend,
            '"""Staff-assistant answer: what to teach HAL',
            "def summarize_widget_census",
            50,
        )
        + "\n```"
    )
    parts.append(
        "### EXTRACT: apex_backend.py — claim actions / improve pack hooks\n```python\n"
        + _extract_lines(backend, "from apex_program_improve_pack import list_claim_actions", None, 80)
        + "\n```"
    )

    improve = REPO / "NewRidgeFinancial2" / "apex_program_improve_pack.py"
    parts.append(
        "### EXTRACT: apex_program_improve_pack.py — claim actions + ERA + huddle\n```python\n"
        + _extract_lines(improve, "ACTION_TYPES = (", "def assess_import_health", 80)
        + "\n```"
    )

    payer = REPO / "NewRidgeFinancial2" / "payer_reference_store.py"
    parts.append(
        "### EXTRACT: payer_reference_store.py — search/load\n```python\n"
        + _extract_lines(payer, '"""Curated dental payer reference', "def format_payer_hits", 90)
        + "\n```"
    )

    payer_json = REPO / "NewRidgeFinancial2" / "data" / "payer_reference.json"
    if payer_json.is_file():
        parts.append(
            "### EXTRACT: payer_reference.json (sample head)\n```json\n"
            + _truncate(payer_json.read_text(encoding="utf-8", errors="replace"), 60)
            + "\n```"
        )

    local_db = REPO / "NewRidgeFinancial2" / "nr2_local_db.py"
    parts.append(
        "### EXTRACT: nr2_local_db.py — office_tasks assignee\n```python\n"
        + _extract_lines(local_db, "assignee TEXT", None, 40)
        + "\n```"
    )

    route = REPO / "NewRidgeFinancial2" / "site" / "hal-route-exec.js"
    parts.append(
        "### EXTRACT: hal-route-exec.js — Remember this prompt\n```js\n"
        + _extract_lines(route, "Tell me what to remember", None, 25)
        + "\n```"
    )

    parts.append(
        """### LIVE FACTS (hal-10464 — consult time)
- HAL answer quoted by operator came from governed memory + payer reference context
  (staff assistant style), NOT from SoftDent write-back or a new automation pack.
- Already shipped IMP-001..010: claim card actions, import health, ERA 835 ingest,
  attachments, daily huddle, batch narratives, EBITDA trend, etc. (NR2-local only).
- Steve = Office Manager (hal-memo-index); Dr. Reno = owner-dentist clinical sign-off.
- office_tasks has assignee field — can assign Steve without SoftDent write-back.
- payer_reference.json curated from Office Insurance.xlsx + SoftDent InsCo labels;
  search via /api/payer-reference + HAL tool search_payer_reference.
- Remember this: → learned_memories.jsonl; governed memories.jsonl can override.
- Fee schedules: fee_schedule_store + /api/fee-schedule; not auto-synced live from SoftDent UI.
- Narratives: HAL drafts → billing review → Dr. Reno sign-off on crowns/implants/SRP;
  HAL never submits to payer.
- Hard rules: never invent $; PHI local; no SoftDent write-back from Apex actions.
- Operator wants: decode what HAL said + coding fixes + REPORT; do not code until approval.
"""
    )
    return "\n\n".join(parts)


def main() -> int:
    key_name, api_key, base_url = resolve_api_and_endpoint()
    if not api_key:
        print("No Moonshot/OpenRouter API key.", file=sys.stderr)
        return 1

    if "moonshot" in (base_url or "").lower():
        model = str(os.getenv("MOONSHOT_MODEL") or "kimi-k2.5").strip()
    else:
        model = str(
            os.getenv("MOONSHOT_MODEL") or os.getenv("KIMI_K2_MODEL") or "moonshotai/kimi-k2"
        ).strip()

    print(f"Using {key_name} @ {base_url} model={model}")
    user = (
        "OPERATOR REQUEST (VERBATIM — do not rewrite):\n\n"
        f"{OPERATOR_REQUEST_VERBATIM}\n\n"
        "Decode what HAL said. How to fix with coding. REPORT only. "
        "CONSULT ONLY — do not apply. Wait for approval.\n\n"
        "## Codebase context\n\n"
        + build_context()
    )

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM},
            {"role": "user", "content": user},
        ],
        "temperature": 1.0,
        "max_tokens": 16000,
    }
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }
    if "openrouter" in base_url.lower():
        headers["HTTP-Referer"] = "https://github.com/NewRidgeFamilyFinancial"
        headers["X-Title"] = "NR2 HAL Said Improve Fix Consult"

    print("Calling Moonshot AI (consult only — will not apply)...")
    req = urllib.request.Request(
        base_url,
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=3600) as resp:
            body = json.loads(resp.read().decode("utf-8"))
        content = extract_message_content(body)
        status = "ok"
    except urllib.error.HTTPError as exc:
        content = f"HTTP {exc.code}: {exc.read().decode('utf-8', errors='replace')[:4000]}"
        status = f"HTTP {exc.code}"
    except Exception as exc:
        content = str(exc)
        status = "error"

    header = (
        f"# Moonshot AI — What HAL Said + Coding Fixes (CONSULT ONLY)\n\n"
        f"**Date:** {DATE}  \n"
        f"**Model:** {model}  \n"
        f"**Key:** {key_name}  \n"
        f"**Endpoint:** {base_url}  \n"
        f"**Status:** {status}  \n"
        f"**Build reviewed:** hal-10464  \n"
        f"**Script:** `scripts/run_moonshot_hal_said_improve_fix_consult.py`  \n"
        f"**Apply:** DO NOT APPLY / DO NOT CODE until operator approves.\n\n"
        f"## Operator request (verbatim)\n\n"
        f"> {OPERATOR_REQUEST_VERBATIM}\n\n"
        f"---\n\n"
    )
    full = header + (content or "(empty)")
    out_file = OUT / f"MOONSHOT_HAL_SAID_IMPROVE_FIX_CONSULT_{DATE}.md"
    doc_file = DOCS / f"MOONSHOT_HAL_SAID_IMPROVE_FIX_CONSULT_{DATE}.md"
    out_file.write_text(full, encoding="utf-8")
    doc_file.write_text(full, encoding="utf-8")
    print(out_file)
    print(doc_file)
    print(f"chars={len(content or '')} status={status}")
    return 0 if status == "ok" else 1


if __name__ == "__main__":
    raise SystemExit(main())
