name: Secrets Scan

on:
  pull_request:
    paths:
      - '**/*'
  schedule:
    - cron: '0 9 * * 1'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks for secrets scanning
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
